### ISSUE TITLE
I downloaded the necessary models and nodes but Marigold is not available. What could be the cause?

### ISSUE THREAD

**Issue by M4gu** [kijai/ComfyUI-Marigold#16]
I downloaded the necessary models and nodes but Marigold is not available. What could be the cause?

![スクリーンショット (464)](https://github.com/kijai/ComfyUI-Marigold/assets/160834453/95fa8fa3-ab97-42f9-8294-a6b3e12f0e78)
![スクリーンショット (465)](https://github.com/kijai/ComfyUI-Marigold/assets/160834453/494369e0-884e-4717-b02e-c936c8aa5925)

**Comment by aphaits** [comment]
![Screenshot 2024-02-27 112954](https://github.com/kijai/ComfyUI-Marigold/assets/132622276/508acc6c-597b-4b04-aedd-df2545e8b925)
also having issues with marigold not being able to run for a couple weeks now

**Comment by kijai** [comment]
I'm going to need to see the error in your startup log, preferably the whole log.

**Comment by aphaits** [comment]
[Log.txt](https://github.com/kijai/ComfyUI-Marigold/files/14436936/Log.txt)

**Comment by kijai** [comment]
> [Log.txt](https://github.com/kijai/ComfyUI-Marigold/files/14436936/Log.txt)

Diffusers version seems to be too old. If you open a command prompt in your folder: F:\StableDiffusion\ComfyUI_windows_portable
and run this command:
`python_embeded\python.exe -m pip list`
You'll see all package versions to confirm the issue.

Installing the minimum working diffusers would be:
`python_embeded\python.exe -m pip install diffusers==0.20.0`

**Comment by aphaits** [comment]
> > [Log.txt](https://github.com/kijai/ComfyUI-Marigold/files/14436936/Log.txt)
> 
> Diffusers version seems to be too old. If you open a command prompt in your folder: F:\StableDiffusion\ComfyUI_windows_portable and run this command: `python_embeded\python.exe -m pip list` You'll see all package versions to confirm the issue.
> 
> Installing the minimum working diffusers would be: `python_embeded\python.exe -m pip install diffusers==0.20.1`

It works! Thank you!
