### ISSUE TITLE
'No checkpoint directory found.'

### ISSUE THREAD

**Issue by GendoG** [kijai/ComfyUI-Marigold#2]
I've followed your setup as described, unpacked the .tar in ComfyUI\custom_nodes\checkpoints but I keep getting this error when it tries to load the diffuser model?

**Comment by kijai** [comment]
It's supposed to be in the checkpoints folder of this node's own folder:
`ComfyUI\custom_nodes\ComfyUI-Marigold\checkpoints`
 or
 `ComfyUI\models\diffusers`

**Comment by GendoG** [comment]
Ah ok, thanks for clarifying! It might be worth updating your Readme with that, this was much clearer. Appreciate your implementation though, thank you!

**Comment by kijai** [comment]
Yes I know, sorry, much work in progress, I was hoping to make it able to load just single file... not sure if it's possible though...
