### ISSUE TITLE
ImportError: cannot import name 'LCMScheduler' from 'diffusers'

### ISSUE THREAD

**Issue by darkpixel** [kijai/ComfyUI-Marigold#24]
When launching Comfy after pulling a few minutes ago, I get:
```
Traceback (most recent call last):
  File "/ai/ComfyUI/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/ai/ComfyUI/custom_nodes/ComfyUI-Marigold/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/ai/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py", line 5, in <module>
    from .marigold.model.marigold_pipeline import MarigoldPipeline
  File "/ai/ComfyUI/custom_nodes/ComfyUI-Marigold/marigold/model/marigold_pipeline.py", line 9, in <module>
    from diffusers import (
ImportError: cannot import name 'LCMScheduler' from 'diffusers' (/ai/ve/comfy/lib/python3.10/site-packages/diffusers/__init__.py)

Cannot import /ai/ComfyUI/custom_nodes/ComfyUI-Marigold module for custom nodes: cannot import name 'LCMScheduler' from 'diffusers' (/ai/ve/comfy/lib/python3.10/site-packages/diffusers/__init__.py)
```

**Comment by kijai** [comment]
> When launching Comfy after pulling a few minutes ago, I get:
> ```
> Traceback (most recent call last):
>   File "/ai/ComfyUI/nodes.py", line 1889, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/ai/ComfyUI/custom_nodes/ComfyUI-Marigold/__init__.py", line 1, in <module>
>     from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "/ai/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py", line 5, in <module>
>     from .marigold.model.marigold_pipeline import MarigoldPipeline
>   File "/ai/ComfyUI/custom_nodes/ComfyUI-Marigold/marigold/model/marigold_pipeline.py", line 9, in <module>
>     from diffusers import (
> ImportError: cannot import name 'LCMScheduler' from 'diffusers' (/ai/ve/comfy/lib/python3.10/site-packages/diffusers/__init__.py)
> 
> Cannot import /ai/ComfyUI/custom_nodes/ComfyUI-Marigold module for custom nodes: cannot import name 'LCMScheduler' from 'diffusers' (/ai/ve/comfy/lib/python3.10/site-packages/diffusers/__init__.py)
> ```

Hmm yeah the diffusers version should be higher now with LCM support. I updated the requirements.txt so either just re-install the nodes or update your diffusers version manually.
