### ISSUE TITLE
macOS half not implemented

### ISSUE THREAD

**Issue by enzyme69** [kijai/ComfyUI-Marigold#9]
I got the Marigold node now, but getting this weird error:
`Error occurred when executing MarigoldDepthEstimation:  "LayerNormKernelImpl" not implemented for 'Half'  File 

Btw, how to get Image Resize node?

**Comment by kijai** [comment]
right, I didn't account for lack of fp16 support... I suppose I have to make that optional

There are a lot of resize nodes, but I like to use the one from this pack:
https://github.com/cubiq/ComfyUI_essentials

**Comment by kijai** [comment]
Ok I made the fp16 optional, disabling that might allow it to run... it does take twice the memory like that though

**Comment by enzyme69** [comment]
It seems to work! Thanks~
